### ISSUE TITLE
using webservice to implementing simple authentication

### ISSUE THREAD

**Issue by pishguy** [Bowman74/fmvvm#12]
with this library how can i get response from server? for example with this code:

```
  Command get incrementCounter {
    _incrementCounter ??= Command(() async{
      final registerResponse = await register(mobileNumber: '123456789');
      print(registerResponse);
    });
    return _incrementCounter;
  }

  Future<dynamic> register({@required String mobileNumber}) async {
    ModelRegister register = ModelRegister(mobile_number: mobileNumber);

    String url = "http://www.xxxxxxx.xxx/api/v1/register";

    final response =
    await http.post(url, body: register.toJson());
    if (response.statusCode == 200) {
      final responseString = jsonDecode(response.body);

      print(responseString);

      return RegisterResponse.fromJson(responseString);
    }
  }

```
`print` function work fine inside ` Future<dynamic> register` but i can't print that inside 

`_incrementCounter ??= Command(() async{}`

**Comment by Bowman74** [comment]
@MahdiPishguy What is the value of the JSON string printed in the register method?

The following code works for me in a command object and does the print:

```
Command get save {
  _save ??= Command(() async {
    var savedEvent = await _galaEventService.saveEvent(_event);
    print(savedEvent);
    _navigationService.navigateBack();
  });
  return _save;
}
```

The result of the print method:

flutter: Instance of 'Event'

**Comment by pishguy** [comment]
@Bowman74 
response is simple json string and i want to show that in for example Text or TextField,

i don't want to use `_navigationService.navigateBack();` because that cause of blacking screen and i'm trying to print inside command, but it doesn't work for me

```
  Command get registerAccount {
    _incrementCounter ??= Command(() async {
      var savedEvent = await register(mobileNumber: '12345678');
      print(savedEvent);
    });
    return _incrementCounter;
  }
```

**I/flutter ( 8651): Instance of 'RegisterResponse'**

**Comment by Bowman74** [comment]
@MahdiPishguy 

I/flutter ( 8651): Instance of 'RegisterResponse' looks correct for using a print statement with an instance of an object. 

Is what you want:

`print(savedEvent.somePropertyThatIWantToCall)`

If you post the json that will have in it the properties that can be called.

**Comment by pishguy** [comment]
@Bowman74 

> [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: Class 'RegisterResponse' has no instance getter 'somePropertyThatIWantToCall'.
> Receiver: Instance of 'RegisterResponse'
> Tried calling: somePropertyThatIWantToCall

**Comment by Bowman74** [comment]
@MahdiPishguy,
somePropertyThatIWantToCall is just something I made up as an example. I'd have to see what the json string is returned from the server to know what the real properties are. :)

Take your code here from the register method:

```
      final responseString = jsonDecode(response.body);

      print(responseString);

      return RegisterResponse.fromJson(responseString);
```

What you are doing is taking an object stored in response.body and converting it to a Json string. That string can then be printed successfully as you are doing on the next line.

Then in the next line you convert it back to an object and return that.

In your calling command you have:

```
      final registerResponse = await register(mobileNumber: '123456789');
      print(registerResponse);
```

So you have the object you returned back and are trying to call print on it, which is why you got the message: I/flutter ( 8651): Instance of 'RegisterResponse'

What you have to do is call a property that exists in registerResponse or convert registerResponse back to a string with jsonDecode and then print the resulting value.

**Comment by pishguy** [comment]
thanks @Bowman74 

my json out put is:

```
{
  "message": "",
  "userInformation": {
    "name": "",
    "avatar": "\/uploads\/users\/2002678401.jpg",
    "teammate": 1,
    "experience": "",
    "age": 66,
    "gender": 0,
    "height": 110,
    "weight": 30,
    "insurance": '',
    "job": '',
    "created_at": "2018-07-03 07:35:18",
    "updated_at": "2019-06-04 13:39:29",
    "api_token": "iEYtIpFk6PvjVIWNmlinM8rLEqk98iLnI0ljcG0qbiKjWTRI0x8tBTHGX3Yk"
  },
  "status": "5"
}
```

and with this code:

```
Future<dynamic> register({@required String mobileNumber}) async {
  ModelRegister register = ModelRegister(mobile_number: mobileNumber);
  String url = "http://www.diabetist.ir/api/v1/register";
  final response = await http.post(url, body: register.toJson());
  if (response.statusCode == 200) {
    return RegisterResponse.fromJson(jsonDecode(response.body));
  }
}
```

i connect to web service and i get json output as i pasted on above, after getting response from server i should store that in database, but in first i should to check `status` in output json, then after return `jsonDecode(response.body)` to `command` as: `var savedEvent = await register(mobileNumber: '12345678');` i need to check `status` and use that on view such as `SnackBar`, for example:


```
builder: (bc) {
  _onWidgetDidBuild(() {
    var status =
    BindingWidget.of<_HomePageViewModel>(bc)
        .getValue('registerStatus') as int;
    
    if(status == 3) {
      Scaffold.of(scaffoldContext).showSnackBar(
        SnackBar(
          content: Text('register successful'),
          backgroundColor: Colors.red,
        ),
      );
    }
  });
  return Container();
}),



  Command get registerAccount {
    _registerStatus ??= Command(() async {
      _registerStatus = await register(mobileNumber: '12345678')
    });
    return _registerStatus['status'] ;
  }



Future<dynamic> register({@required String mobileNumber}) async {
  ModelRegister register = ModelRegister(mobile_number: mobileNumber);
  String url = "http://www.diabetist.ir/api/v1/register";
  final response = await http.post(url, body: register.toJson());
  if (response.statusCode == 200) {

    final responseString = jsonDecode(response.body);

   /* store in database if status on `responseString` is for example 3 */
   /* store in database */

    return RegisterResponse.fromJson(responseString);

  }
}
```

**Comment by Bowman74** [comment]
I'm not 100% sure what RegisterResponse looks like, should it be?

`return _registerStatus.status;`

?

Also is registerStatus a property on your view model?

**Comment by pishguy** [comment]
@Bowman74 yes i found whats problem of my implementation, thanks a lot sir

**Comment by pishguy** [comment]
@Bowman74 i have another question, can i implementing `socket.io` with this library?
