### ISSUE TITLE
showing snackbar or toast with multiple click on Button and calling BindingWidget

### ISSUE THREAD

**Issue by pishguy** [Bowman74/fmvvm#15]
I'm not sure but i think this is a bug on this library, after multiple click on `FloatingActionButton` this  `BindingWidget` call once, for example:

```
BindingWidget<_HomePageViewModel>(
    bindings: <Binding>[
      Binding('registerStatus', bindableBase,
          _HomePageViewModel.registerStatusProperty,
          bindingDirection: BindingDirection.TwoWay,
          valueConverter: _NumberValueConverter())
    ],
    builder: (bc) {
      print('BEFORE Future');
      Future(() {
        var registerStatus =
        BindingWidget.of<_HomePageViewModel>(bc)
            .getValue('registerStatus') as String;
        switch (int.parse(registerStatus)) {
          case 1:
            Scaffold.of(scaffoldContext).showSnackBar(SnackBar(
              content: Text('test'),
            ));
            break;
        }
        print('clicked');
      });
      print('AFTER Future');
      return Container();
    }),
```

output in console:

**single click:**

> I/flutter (24357): 0) 200 // is printed on view model, thats only status of http connection response
> I/flutter (24357): BEFORE Future 
> I/flutter (24357): AFTER Future
> I/flutter (24357): clicked

**multiple click**
> I/flutter (24357): 0) 200 // is printed on view model, thats only status of http connection response
> I/flutter (24357): BEFORE Future 
> I/flutter (24357): AFTER Future
> I/flutter (24357): clicked
> I/flutter (24357): 0) 200 // is printed on view model, thats only status of http connection response
> I/flutter (24357): 0) 200 // is printed on view model, thats only status of http connection response
> I/flutter (24357): 0) 200 // is printed on view model, thats only status of http connection response
> I/flutter (24357): 0) 200 // is printed on view model, thats only status of http connection response
> I/flutter (24357): 0) 200 // is printed on view model, thats only status of http connection response
> I/flutter (24357): 0) 200 // is printed on view model, thats only status of http connection response
> I/flutter (24357): 0) 200 // is printed on view model, thats only status of http connection response
> I/flutter (24357): 0) 200 // is printed on view model, thats only status of http connection response
> I/flutter (24357): 0) 200 // is printed on view model, thats only status of http connection response
> I/flutter (24357): 0) 200 // is printed on view model, thats only status of http connection response

**full source code:**

http://paste.debian.net/1086295/

-------**UPDATE**-------

i change `toast` and `snackbar` with `text` and `text` work fine without problem, but `snakebar` don't show on multiple click on `floatingActionButton`

```
builder: (bc) {
  var registerStatus =
      BindingWidget.of<_HomePageViewModel>(bc)
          .getValue('registerStatus') as String;
  return Text(
    registerStatus,
    style: TextStyle(fontSize: 20.0),
  );
});
```

command:

```
Command get registerAccount {
    _registerStatus ??= Command(() async {
      registerStatus++;
    });
    return _registerStatus;
}
```

**Comment by Bowman74** [comment]
@MahdiPishguy 
Based on your switch status you would only show the snackbar if the registrationStatus is one and you keep incrementing it. That's my guess on why you only see it once, when the value is one.

**Comment by pishguy** [comment]
@Bowman74 i removed switch and check again. not any change

**Comment by Bowman74** [comment]
@MahdiPishguy,
Do you have the full repository. If I can run your code I'm sure i can find the problem. Don't forget a change event will only happen if the data in the property has changed. If registration status is just being set to the same value over and over again, no refresh may happen.

**Comment by Bowman74** [comment]
@MahdiPishguy I'm going to close this issue. Let me know if you've had any additional problems with it.
